#!/usr/bin/env python3
"""Build a deterministic Lua name database from Wago ItemSparse CSV or nexus JSON.
Only Python's standard library is needed. No game-client file is modified.
"""
import argparse
import csv
import hashlib
import html
import io
import json
from pathlib import Path
import re
import tempfile
import os
import urllib.request


def lua_string(value):
    # Lua 5.1 has decimal escapes, not JSON's \uXXXX escape notation.
    out = []
    for char in str(value):
        if char in ('"', '\\'):
            out.append('\\' + char)
        elif ord(char) < 32 or ord(char) == 127:
            out.append('\\%03d' % ord(char))
        else:
            out.append(char)
    return '"' + ''.join(out) + '"'


def collect(raw, fmt):
    text = raw.decode('utf-8-sig')
    if fmt == 'csv':
        reader = csv.DictReader(io.StringIO(text))
        if not reader.fieldnames or not {'ID', 'Display_lang'} <= set(reader.fieldnames):
            raise ValueError('CSV must have ID and Display_lang columns (Wago ItemSparse, enUS).')
        records = ((row['ID'], row['Display_lang']) for row in reader)
    else:
        data = json.loads(text)
        if not isinstance(data, list):
            raise ValueError('Expected a nexus-devs item JSON array.')
        records = ((row['itemId'], html.unescape(row['name'])) for row in data)
    names = {}
    for raw_id, name in records:
        item_id = int(raw_id)
        if item_id <= 0 or item_id > 2147483647:
            raise ValueError('Invalid item ID: %r' % raw_id)
        if not name or not name.strip():
            continue  # DB2 includes unused rows with no display name.
        if any(ord(c) < 32 or ord(c) == 127 or c == '|' for c in name):
            raise ValueError('Unsafe name for item %s' % item_id)
        if len(name.encode('utf-8')) > 255:
            raise ValueError('Name is too long for item %s' % item_id)
        if item_id in names and names[item_id] != name:
            raise ValueError('Conflicting names for item %s' % item_id)
        names[item_id] = name
    if not names:
        raise ValueError('No names were found; existing output has not been changed.')
    return names


def render(names, build, source, coverage, digest):
    lines = ['-- Generated by tools/build_names.py. Do not edit; use /el set for overrides.',
             'local _, ns = ...', 'ns.ItemNamesMeta = {']
    for k, v in {'locale': 'enUS', 'build': build, 'source': source,
                 'coverage': coverage, 'sha256': digest}.items():
        lines.append('    %s = %s,' % (k, lua_string(v)))
    lines += ['    count = %d,' % len(names), '}', 'ns.ItemNames = {']
    lines += ['    [%d] = %s,' % (key, lua_string(names[key])) for key in sorted(names)]
    lines += ['}', '']
    return '\n'.join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    source = p.add_mutually_exclusive_group(required=True)
    source.add_argument('--input', type=Path, help='Local enUS CSV or nexus JSON')
    source.add_argument('--download', action='store_true', help='Download Wago ItemSparse for --build')
    p.add_argument('--format', choices=['csv', 'json'], default='csv')
    p.add_argument('--build', required=True, help='Exact Forever x.x.x.x build; or fallback dataset label')
    p.add_argument('--source', help='Source URL / provenance for local input')
    p.add_argument('--coverage', choices=['forever', 'classic-fallback'], default='forever')
    p.add_argument('--output', type=Path, default=Path('EnglishLinks/ItemNames_enUS.lua'))
    args = p.parse_args()
    if args.download:
        if args.format != 'csv' or not re.fullmatch(r'1\.60\.\d+\.\d+', args.build):
            p.error('--download requires CSV and an explicit Forever 1.60.x.x build')
        url = 'https://wago.tools/db2/ItemSparse/csv?build=' + args.build + '&locale=enUS'
        try:
            with urllib.request.urlopen(url, timeout=60) as response:
                raw = response.read()
        except Exception as exc:
            p.exit(1, 'Download failed: %s\nExport ItemSparse/enUS CSV from Wago and use --input.\n' % exc)
        provenance = url
    else:
        raw = args.input.read_bytes()
        provenance = args.source or args.input.name
    try:
        names = collect(raw, args.format)
    except (ValueError, KeyError, TypeError, UnicodeError) as exc:
        p.exit(1, 'Invalid data: %s\n' % exc)
    result = render(names, args.build, provenance, args.coverage, hashlib.sha256(raw).hexdigest())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # A failed parse/download never overwrites a working database.
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
                                     dir=args.output.parent, delete=False) as target:
        temporary = Path(target.name)
        target.write(result)
    try:
        os.replace(temporary, args.output)
    finally:
        temporary.unlink(missing_ok=True)
    print('%d names -> %s (%s)' % (len(names), args.output, args.coverage))


if __name__ == '__main__':
    main()
