#!/usr/bin/env python3
"""Build signed rand-ID names from a pinned Wowhead Forever gear-planner response.

Default operation is offline. --fetch explicitly refreshes the raw snapshot and
tooltip evidence; it never downloads Classic/Retail data as a substitute.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import urllib.request
import zipfile
from build_wowhead import literal
from build_packs import lua, name_ok

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'https://nether.wowhead.com/forever/data/gear-planner?dv=59&db=1790292378'
TABLE = 'wow.gearPlanner.classicplus.randomEnchant'
PROBES = [(6614, None), (6614, 763), (10378, None), (10378, 1215),
          (10378, -68), (6614, -9), (10378, -7)]


def parse(text):
    marker = 'WH.setPageData(' + json.dumps(TABLE) + ','
    if text.count(marker) != 1:
        raise ValueError('Missing or ambiguous Forever randomEnchant table')
    def unique(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError('Duplicate data key')
            result[key] = value
        return result
    rows = json.loads(literal(text, text.index(marker) + len(marker)), object_pairs_hook=unique)
    names = {}
    for key, row in rows.items():
        if not re.fullmatch(r'-?[1-9]\d*', key):
            raise ValueError('Invalid signed rand ID')
        rid = int(key)
        if abs(rid) > 2147483647 or type(row.get('id')) is not int or row['id'] != rid:
            raise ValueError('Mismatched rand ID')
        name = row.get('name')
        if not isinstance(name, str) or not name_ok(name):
            raise ValueError('Unsafe rand name')
        names[rid] = name
    if not names:
        raise ValueError('Empty rand table')
    return names


def compile_snapshot(directory):
    manifest = json.loads((directory / 'manifest.json').read_text())
    archive = directory / 'snapshot.zip'
    if manifest['edition'] != 'Wowhead Forever' or manifest['locale'] != 'enUS':
        raise ValueError('Wrong source edition/locale')
    if hashlib.sha256(archive.read_bytes()).hexdigest() != manifest['archive_sha256']:
        raise ValueError('Snapshot checksum mismatch')
    names, probes = None, []
    with zipfile.ZipFile(archive) as z:
        for source in manifest['files']:
            if not source['url'].startswith('https://nether.wowhead.com/forever/'):
                raise ValueError('Not a Forever source')
            raw = z.read(source['file'])
            if hashlib.sha256(raw).hexdigest() != source['sha256']:
                raise ValueError('Source checksum mismatch')
            if source['parser'] == 'randomEnchant':
                if names is not None:
                    raise ValueError('Multiple rand tables')
                names = parse(raw.decode('utf-8'))
            elif source['parser'] == 'tooltip':
                probes.append((source, json.loads(raw)))
            else:
                raise ValueError('Unknown source parser')
    if not names:
        raise ValueError('Missing rand data')
    bases = {s['item_id']: p['name'] for s, p in probes if s['rand_id'] is None}
    for source, payload in probes:
        rid = source['rand_id']
        expected = bases[source['item_id']]
        if rid in names:
            expected += ' ' + names[rid]
        if payload['name'] != expected:
            raise ValueError('Tooltip contradicts signed rand mapping')
    return names, manifest


def render(names, manifest):
    return ('-- Generated by tools/build_random_affixes.py; Wowhead Forever signed rand IDs.\n'
            'local _, ns = ...\nns.ItemRandomAffixes = ' + lua(names) + '\n'
            'ns.ItemRandomAffixesMeta = ' + lua({
                'count': len(names), 'source': 'Wowhead Forever',
                'archiveSHA256': manifest['archive_sha256'],
            }) + '\n')


def fetch(directory):
    if (directory / 'snapshot.zip').exists() or (directory / 'manifest.json').exists():
        raise FileExistsError('Preserve the existing snapshot; use a new --source-dir')
    directory.mkdir(parents=True, exist_ok=True)
    requests = [('gear-planner.js', SOURCE, 'randomEnchant', {})]
    for item, rand in PROBES:
        tail = '' if rand is None else '?rand=' + str(rand)
        requests.append((f'tooltip-{item}-{rand}.json',
                         f'https://nether.wowhead.com/forever/tooltip/item/{item}{tail}',
                         'tooltip', {'item_id': item, 'rand_id': rand}))
    manifest = {'edition': 'Wowhead Forever', 'locale': 'enUS', 'exact_build': None,
                'table': TABLE, 'files': []}
    archive = directory / 'snapshot.zip'
    with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as z:
        for filename, url, parser, extra in requests:
            started = datetime.now(timezone.utc).isoformat()
            with urllib.request.urlopen(url, timeout=30) as response:
                raw = response.read()
            retrieved = datetime.now(timezone.utc).isoformat()
            info = zipfile.ZipInfo(filename, (2026, 10, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, raw)
            manifest['files'].append({'file': filename, 'url': url, 'parser': parser,
                                      'retrieval_started_at': started,
                                      'retrieved_at': retrieved, 'bytes': len(raw),
                                      'sha256': hashlib.sha256(raw).hexdigest(), **extra})
            print('Fetched', filename, flush=True)
    manifest['archive_sha256'] = hashlib.sha256(archive.read_bytes()).hexdigest()
    (directory / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--fetch', action='store_true')
    p.add_argument('--source-dir', type=Path, default=ROOT / 'data/random-affix-sources')
    args = p.parse_args()
    directory = args.source_dir
    if args.fetch:
        fetch(directory)
    names, manifest = compile_snapshot(directory)
    (ROOT / 'EnglishLinks/RandomAffixes_enUS.lua').write_text(render(names, manifest))
    print(json.dumps({'count': len(names), 'positive': sum(i > 0 for i in names),
                      'negative': sum(i < 0 for i in names),
                      'distinct_names': len(set(names.values()))}))


if __name__ == '__main__':
    main()
